// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD7fDnzlIJ0UYAFJ3yRRaz5z146Zoaj8Y',
    appId: '1:253117870961:web:248c7d5bc31635cbd37cd0',
    messagingSenderId: '253117870961',
    projectId: 'todo-c9463',
    authDomain: 'todo-c9463.firebaseapp.com',
    storageBucket: 'todo-c9463.appspot.com',
    measurementId: 'G-1GR6Q3NGG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCERH0N6Al5g87oTykjt4pYPkVsVqslFPY',
    appId: '1:253117870961:android:fd0ca2f4de238c1ad37cd0',
    messagingSenderId: '253117870961',
    projectId: 'todo-c9463',
    storageBucket: 'todo-c9463.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9f5gIbL9YNsHEQ7TB4vXbzupzDsTSO8w',
    appId: '1:253117870961:ios:76fb09afe0228695d37cd0',
    messagingSenderId: '253117870961',
    projectId: 'todo-c9463',
    storageBucket: 'todo-c9463.appspot.com',
    iosClientId: '253117870961-6bp701fi1p8i591mt2lgda5ssekh9hde.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9f5gIbL9YNsHEQ7TB4vXbzupzDsTSO8w',
    appId: '1:253117870961:ios:76fb09afe0228695d37cd0',
    messagingSenderId: '253117870961',
    projectId: 'todo-c9463',
    storageBucket: 'todo-c9463.appspot.com',
    iosClientId: '253117870961-6bp701fi1p8i591mt2lgda5ssekh9hde.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
